In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler 
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE
from sklearn.metrics import precision_score,recall_score,f1_score

### Import the required libraries and modules that you would need.

### Read that data into Python and call the dataframe donors.

In [2]:
numerical = pd.read_csv('numerical7_02.csv')
numerical = numerical.drop(['Unnamed: 0'], axis = 1)


In [3]:
categorical = pd.read_csv('categorical7_02.csv')
categorical = categorical.drop(['Unnamed: 0'], axis = 1)


In [4]:
Ydatat = pd.read_csv('target7_02.csv')
datatarget = Ydatat.drop(['Unnamed: 0','TARGET_D'], axis = 1)
datatarget

TARGET_B
0             0
1             0
2             0
3             0
4             0
...         ...
95407         0
95408         0
95409         0
95410         1
95411         0

[95412 rows x 1 columns]

In [5]:
donors = pd.concat([numerical, categorical,datatarget], axis=1)

In [6]:
#dropping columns 
donors = donors.drop(['ADATE_2','ADATE_3','ADATE_4','ADATE_6','ADATE_7','ADATE_8','ADATE_9','ADATE_11','ADATE_12','ADATE_14','ADATE_16','ADATE_18','NEXTDATE'],axis=1)

In [7]:
donors

ODATEDW  TCODE   DOB        AGE  INCOME  WEALTH1  HIT  MALEMILI  \
0         8901      0  3712  60.000000     5.0      5.0    0         0   
1         9401      1  5202  46.000000     6.0      9.0   16         0   
2         9001      1     0  61.611649     3.0      1.0    2         0   
3         8701      0  2801  70.000000     1.0      4.0    2         0   
4         8601      0  2001  78.000000     3.0      2.0   60         1   
...        ...    ...   ...        ...     ...      ...  ...       ...   
95407     9601      1     0  61.611649     5.0      5.0    0        14   
95408     9601      1  5001  48.000000     7.0      9.0    1         0   
95409     9501      1  3801  60.000000     5.0      5.0    0         0   
95410     8601      0  4005  58.000000     7.0      5.0    0         0   
95411     8801      2  1801  80.000000     5.0      8.0    3         1   

       MALEVET  VIETVETS  ...  GENDER  DATASRCE  SOLIH  VETERANS  RFA_2R  \
0           39        34  ...       F         3    NaN       NaN       L   
1           15        55  ...       M         3    NaN       NaN       L   
2           20        29  ...       M         3    NaN       NaN       L   
3           23        14  ...       F         3    NaN       NaN       L   
4           28         9  ...       F         3   12.0       NaN       L   
...        ...       ...  ...     ...       ...    ...       ...     ...   
95407       36        47  ...       M         3    NaN       NaN       L   
95408       31        43  ...       M         3    NaN       NaN       L   
95409       18        46  ...       M         3    NaN       NaN       L   
95410       28        35  ...       F         2   12.0       NaN       L   
95411       33        22  ...       F         3   12.0       NaN       L   

       RFA_2A  GEOCODE2  DOMAIN_A  DOMAIN_B  TARGET_B  
0           E         C         T         2         0  
1           G         A         S         1         0  
2           E         C         R         2         0  
3           E         C         R         2         0  
4           F         A         S         2         0  
...       ...       ...       ...       ...       ...  
95407       G         C         C         2         0  
95408       F         A         C         1         0  
95409       E         B         C         3         0  
95410       F         A         C         1         1  
95411       G         C         C         1         0  

[95412 rows x 335 columns]

In [8]:
nas = pd.Series(donors.isna().sum())
nas[nas==0]

ODATEDW     0
TCODE       0
DOB         0
AGE         0
INCOME      0
           ..
RFA_2A      0
GEOCODE2    0
DOMAIN_A    0
DOMAIN_B    0
TARGET_B    0
Length: 333, dtype: int64

### Check the datatypes of all the columns in the data

In [9]:
donors.dtypes

ODATEDW       int64
TCODE         int64
DOB           int64
AGE         float64
INCOME      float64
             ...   
RFA_2A       object
GEOCODE2     object
DOMAIN_A     object
DOMAIN_B      int64
TARGET_B      int64
Length: 335, dtype: object

### Check for null values in the dataframe. Replace the null values using the methods learned in class.

In [10]:
#done in previus labs. dropping both column which there is a high number of null values
donors = donors.drop(['SOLIH','VETERANS'],axis=1)




### Split the data into numerical and catagorical. Decide if any columns need their dtype changed.

In [11]:
numerical = donors.select_dtypes(np.number)
categorical = donors.select_dtypes(object)

### Split the data into a training set and a test set

In [12]:
X = donors.drop(["TARGET_B"], axis = 1)
y = donors['TARGET_B']

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Scale the features either by using normalizer or a standard scaler.

In [14]:
#X_num = X.select_dtypes(include = np.number)
#X_cat = X.select_dtypes(include = object)

In [15]:
#split the train test into numerical and categorical
numerical = X_train.select_dtypes(include = np.number)
categorical = X_train.select_dtypes(include = object)

In [16]:
#normalizing numerical columns
from sklearn.preprocessing import MinMaxScaler
transformer = MinMaxScaler().fit(numerical)
X_normalized = transformer.transform(numerical)
X_normalized = pd.DataFrame(X_normalized, columns=numerical.columns)
X_normalized.head()

ODATEDW     TCODE       DOB       AGE    INCOME   WEALTH1       HIT  \
0  0.928315  0.000389  0.000000  0.624862  0.666667  0.555556  0.000000   
1  0.498208  0.000000  0.350257  0.649485  0.500000  0.555556  0.000000   
2  0.354839  0.000014  0.360556  0.639175  1.000000  0.666667  0.008299   
3  0.354839  0.000028  0.267868  0.731959  0.166667  0.555556  0.000000   
4  0.426523  0.000000  0.000000  0.624862  0.000000  0.555556  0.000000   

   MALEMILI   MALEVET  VIETVETS  ...  FISTDATE   TIMELAG   AVGGIFT  CONTROLN  \
0       0.0  0.292929  0.363636  ...  0.999896  0.008272  0.013732  0.472526   
1       0.0  0.232323  0.232323  ...  0.938248  0.000919  0.013277  0.098807   
2       0.0  0.252525  0.272727  ...  0.917318  0.012868  0.004407  0.307856   
3       0.0  0.343434  0.191919  ...  0.917213  0.020221  0.005610  0.429001   
4       0.0  0.373737  0.464646  ...  0.927835  0.005515  0.010585  0.733875   

   HPHONE_D    RFA_2F  CLUSTER2   CLUSTER  DATASRCE  DOMAIN_B  
0       1.0  0.000000  0.426230  0.019231       1.0  0.000000  
1       0.0  0.333333  0.950820  0.192308       0.5  0.000000  
2       1.0  0.333333  0.852459  0.673077       1.0  0.333333  
3       1.0  0.000000  0.344262  0.384615       0.5  0.666667  
4       1.0  0.000000  0.688525  0.807692       0.5  0.333333  

[5 rows x 325 columns]

### Encode the categorical features using One-Hot Encoding or Ordinal Encoding

In [17]:
#encoder categorical features
from sklearn.preprocessing import OneHotEncoder
X_cat = categorical.copy()
encoder = OneHotEncoder(handle_unknown='error',drop='first').fit(X_cat)
encoded = encoder.transform(X_cat).toarray()
onehot_encoded = pd.DataFrame(encoded,columns=encoder.get_feature_names_out(X_cat.columns))
onehot_encoded.head()

STATE_FL  STATE_GA  STATE_IL  STATE_IN  STATE_MI  STATE_MO  STATE_NC  \
0       0.0       0.0       1.0       0.0       0.0       0.0       0.0   
1       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
2       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
3       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
4       0.0       0.0       0.0       0.0       0.0       0.0       0.0   

   STATE_TX  STATE_WA  STATE_WI  ...  RFA_2A_E  RFA_2A_F  RFA_2A_G  \
0       0.0       0.0       0.0  ...       0.0       1.0       0.0   
1       1.0       0.0       0.0  ...       0.0       1.0       0.0   
2       0.0       0.0       0.0  ...       1.0       0.0       0.0   
3       0.0       0.0       0.0  ...       1.0       0.0       0.0   
4       0.0       0.0       0.0  ...       0.0       1.0       0.0   

   GEOCODE2_B  GEOCODE2_C  GEOCODE2_D  DOMAIN_A_R  DOMAIN_A_S  DOMAIN_A_T  \
0         0.0         0.0         0.0         0.0         0.0         0.0   
1         0.0         0.0         1.0         0.0         1.0         0.0   
2         0.0         0.0         1.0         0.0         0.0         1.0   
3         0.0         0.0         0.0         0.0         1.0         0.0   
4         1.0         0.0         0.0         1.0         0.0         0.0   

   DOMAIN_A_U  
0         1.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0  

[5 rows x 27 columns]

In [18]:
#concatenating categorical and numerical values after normalizing and encoding.
X_train_treated = pd.concat([X_normalized,onehot_encoded],axis=1)
X_train_treated.tail()

ODATEDW     TCODE       DOB       AGE    INCOME   WEALTH1       HIT  \
76324  0.862366  0.000000  0.000000  0.624862  0.000000  0.777778  0.000000   
76325  0.713262  0.000014  0.370855  0.628866  0.166667  0.222222  0.024896   
76326  0.569892  0.000000  0.556231  0.443299  0.666667  0.555556  0.000000   
76327  0.784946  0.000000  0.000000  0.624862  0.166667  0.555556  0.000000   
76328  0.641577  0.000000  0.495366  0.494845  0.500000  0.555556  0.000000   

       MALEMILI  MALEVET  VIETVETS  ...  RFA_2A_E  RFA_2A_F  RFA_2A_G  \
76324  0.000000  0.00000  0.000000  ...       0.0       0.0       1.0   
76325  0.020202  0.40404  0.313131  ...       0.0       1.0       0.0   
76326  0.020202  0.40404  0.555556  ...       0.0       1.0       0.0   
76327  0.000000  0.30303  0.222222  ...       0.0       1.0       0.0   
76328  0.000000  0.20202  0.545455  ...       1.0       0.0       0.0   

       GEOCODE2_B  GEOCODE2_C  GEOCODE2_D  DOMAIN_A_R  DOMAIN_A_S  DOMAIN_A_T  \
76324         0.0         0.0         0.0         0.0         0.0         0.0   
76325         1.0         0.0         0.0         0.0         1.0         0.0   
76326         1.0         0.0         0.0         0.0         1.0         0.0   
76327         0.0         0.0         1.0         1.0         0.0         0.0   
76328         0.0         0.0         0.0         0.0         0.0         0.0   

       DOMAIN_A_U  
76324         0.0  
76325         0.0  
76326         0.0  
76327         0.0  
76328         0.0  

[5 rows x 352 columns]

#### X_TEST

In [19]:
#getting values for the test and transforming it
X_test_num = X_test.select_dtypes(np.number)


In [20]:
numTest_treated = transformer.transform(X_test_num)
numTest_treated = pd.DataFrame(numTest_treated, columns=X_test_num.columns)

In [21]:
# Encoding categorical features using One-Hot Encoding 
X_test_cat = X_test.select_dtypes(object)
encoded = encoder.transform(X_test_cat).toarray()
onehot_encoded = pd.DataFrame(encoded,columns=encoder.get_feature_names_out(X_test_cat.columns))


In [22]:
# concatenating categorical and numerical once after being onehot_encoded and transformed
X_test_treated = pd.concat([numTest_treated,onehot_encoded],axis=1)

In [23]:
# Fit a logistic regression model on the training data.
classification = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr',max_iter=1000)
classification.fit(X_train_treated, y_train)
predictions = classification.predict(X_test_treated)
confusion_matrix(y_test, predictions)

array([[18105,     0],
       [  978,     0]], dtype=int64)

### Check the accuracy on the test data.

In [25]:
18105/(18105+978)
#94% percent the target is 0 and the other is 6 %

0.9487501965099827

In [28]:
# reseting the target index
y_train = y_train.reset_index(drop=True)
X_train0 = X_train_treated[y_train == 0]
X_train1 = X_train_treated[y_train == 1]


### Undersamplin

In [29]:
from sklearn.utils import resample
X_train0_under = resample(X_train0, 
                                   replace=False, 
                                   n_samples = len(X_train1))

In [30]:
train_downsampled = pd.concat([X_train0_under, X_train1], axis=0).reset_index(drop=True)
y_downsample = pd.Series(len(X_train0_under)*[0]+len(X_train1)*[1])

In [31]:
# Fit a logistic regression model on the training data.
classification = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr',max_iter=1000)
classification.fit(train_downsampled, y_downsample)

predictions = classification.predict(X_test_treated)

confusion_matrix(y_test, predictions)

array([[10793,  7312],
       [  422,   556]], dtype=int64)

In [32]:
classification.score(X_test_treated, y_test)

0.5947178116648326

### Oversamplin

In [33]:
X_train1_over = resample(X_train1, 
                                   replace=True, 
                                   n_samples = len(X_train0))

In [34]:
train_oversample = pd.concat([X_train0, X_train1_over], axis=0).reset_index(drop=True)
y_oversample = pd.Series(len(X_train0)*[0]+len(X_train1_over)*[1])

In [35]:
# Fit a logistic regression model on the training data.
classification = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr',max_iter=250)
classification.fit(train_oversample, y_oversample)

predictions = classification.predict(X_test_treated)
confusion_matrix(y_test, predictions)

C:\Users\Manuel Buendía\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[11169,  6936],
       [  440,   538]], dtype=int64)

In [36]:
classification.score(X_test_treated, y_test)
#oversample makes better results

0.6134779646806058

### smote

In [37]:
sm = SMOTE(random_state=100, k_neighbors=3)
X_train_SMOTE,y_train_SMOTE = sm.fit_resample(X_train_treated,y_train)
LR = LogisticRegression(random_state=0, solver='lbfgs') 
LR.fit(X_train_SMOTE, y_train_SMOTE) 
pred = LR.predict(X_test_treated)
print("precision: ",precision_score(y_test,pred))
print("recall: ",recall_score(y_test,pred))
print("f1: ",f1_score(y_test,pred))

precision:  0.06962519521082769
recall:  0.5470347648261759
f1:  0.12352805356730548


C:\Users\Manuel Buendía\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [38]:
confusion_matrix(y_test, predictions)

array([[11169,  6936],
       [  440,   538]], dtype=int64)

In [41]:
sm = SMOTE(random_state=100, k_neighbors=4)
X_train_SMOTE,y_train_SMOTE = sm.fit_resample(X_train_treated,y_train)
LR = LogisticRegression(random_state=0, solver='lbfgs') 
LR.fit(X_train_SMOTE, y_train_SMOTE) 
pred = LR.predict(X_test_treated)
print("precision: ",precision_score(y_test,pred))
print("recall: ",recall_score(y_test,pred))
print("f1: ",f1_score(y_test,pred))

precision:  0.07076276749376395
recall:  0.5511247443762781
f1:  0.12542175683536938


C:\Users\Manuel Buendía\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [42]:
confusion_matrix(y_test, predictions)

array([[11169,  6936],
       [  440,   538]], dtype=int64)

In [43]:
sm = SMOTE(random_state=100, k_neighbors=1)
X_train_SMOTE,y_train_SMOTE = sm.fit_resample(X_train_treated,y_train)
LR = LogisticRegression(random_state=0, solver='lbfgs') 
LR.fit(X_train_SMOTE, y_train_SMOTE) 
pred = LR.predict(X_test_treated)
print("precision: ",precision_score(y_test,pred))
print("recall: ",recall_score(y_test,pred))
print("f1: ",f1_score(y_test,pred))

precision:  0.06956177402323126
recall:  0.5388548057259713
f1:  0.12321720832359132


C:\Users\Manuel Buendía\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [44]:
confusion_matrix(y_test, predictions)

array([[11169,  6936],
       [  440,   538]], dtype=int64)